v3
VirgilSecurity/virgil-passw0rd-php pull request #30
Opened 2020-03-19 22:31 UTC by PetrenkoAnton

2020-03-31 09:04 UTC, nau11713 submitted a review, later dismissed

2020-03-31 09:38 UTC, nau11713 submitted a review, later dismissed

2020-04-03 16:36 UTC, SanjoDeundiak requested changes

2020-04-03 16:36 UTC, SanjoDeundiak commented on src/Http/HttpBaseClient.php
> +                    'debug' => $this->debug
What is that for?

2020-04-03 16:36 UTC, SanjoDeundiak commented on src/Http/Request/Phe/EnrollRequest.php
> +    public function __construct(AvailableRequest $request, int $version)
AvailableRequest should be moved either to the Client, or fixed in EnrollRequest (and others)

2020-04-03 16:36 UTC, SanjoDeundiak commented on src/Pure/Storage/MariaDbPureStorage.php
> +            // TODO! Add throwable
Fix Todos

2020-04-03 16:36 UTC, SanjoDeundiak commented on src/Pure/Storage/MariaDbPureStorage.php
> +            $conn->beginTransaction();
where is $conn->commit()?

2020-04-03 16:36 UTC, SanjoDeundiak commented on src/Pure/Storage/MariaDbPureStorage.php
> +            // TODO: Proper StringBuilder size
FIX

2020-04-07 10:49 UTC, SanjoDeundiak requested changes

2020-04-07 10:49 UTC, SanjoDeundiak commented on tests/PureTest.php
> +     * @group f
?

2020-04-07 10:49 UTC, SanjoDeundiak commented on src/Http/HttpPureClient.php
> +        $endpoint = sprintf("/update-user", $request->getUserId());
This is very wrong

2020-04-07 14:09 UTC, SanjoDeundiak approved these changes

2020-04-07 14:54 UTC, merged